# Use root/example as user/password credentials

version: '3.1'

services:

  db:
    image: mysql:5.7
    volumes:
      - ./mysql/:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: 'foodBlog'
      MYSQL_USER: 'sara'
      MYSQL_PASSWORD: 'AfQwdXhJ1uynNV8sq'
      MYSQL_ROOT_PASSWORD: 'AfQwdXhJ1uynNV8sq'
      MYSQL_HOST: 'db'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: 'AfQwdXhJ1uynNV8sq'  
    links:
      - db

volumes:
  db: