# Generated by Django 3.0.6 on 2020-06-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Chef')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('experience', models.IntegerField(verbose_name='Experience')),
                ('greduated_from', models.CharField(max_length=50, verbose_name='Graduated')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('recipe', models.TextField(verbose_name='Recipe')),
                ('ingredients', models.TextField(verbose_name='Ingredients')),
                ('cook_image', models.ImageField(upload_to='partials/images', verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('authors', models.ManyToManyField(to='stories.Author', verbose_name='Author')),
            ],
        ),
    ]
