# Generated by Django 3.0.6 on 2020-06-06 10:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='greduated_from',
            new_name='graduated_from',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(default='', verbose_name='Directions'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(default='', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prepare_time',
            field=models.TimeField(default=datetime.time(16, 0), verbose_name='Prepate time'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='authors',
            field=models.ManyToManyField(to='stories.Author', verbose_name='Authors'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=50, verbose_name='By')),
                ('description', models.TextField(verbose_name='Description')),
                ('commented_at', models.DateField(auto_now_add=True, verbose_name='Commented at')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Recipe', verbose_name='Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_category', models.CharField(max_length=50, verbose_name='Recipe category')),
                ('recipes', models.ManyToManyField(to='stories.Recipe', verbose_name='Recipes')),
            ],
        ),
    ]
