# Generated by Django 3.0.6 on 2020-06-21 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cover_image',
            field=models.ImageField(default='bg_4.jpg', upload_to='stories', verbose_name='Cover image'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='users',
            field=models.ManyToManyField(related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(default='images/bg_4.jpg', upload_to='stories', verbose_name='Cover image'),
        ),
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
