# Generated by Django 3.0.6 on 2020-06-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20200606_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(default='', verbose_name='Description')),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='cook_image',
            new_name='recipe_image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='notes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='Comment_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('commented_at', models.DateField(auto_now_add=True, verbose_name='Commented at')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Comment', verbose_name='Comment')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='stories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stories.Story', verbose_name='Story'),
        ),
    ]
