# Generated by Django 3.0.7 on 2020-07-01 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_sumnumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Story image'),
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_image', models.ImageField(upload_to='stories/', verbose_name='Story image')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Story')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
    ]
