# Generated by Django 3.0.7 on 2020-07-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20200701_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyimage',
            options={'verbose_name': 'Story Image', 'verbose_name_plural': 'Story Images'},
        ),
        migrations.RenameField(
            model_name='storyimage',
            old_name='story_image',
            new_name='images',
        ),
    ]
