# Generated by Django 3.0.6 on 2020-06-22 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0004_auto_20200621_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='users',
            field=models.ManyToManyField(null=True, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
