# Generated by Django 3.0.6 on 2020-06-07 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20200606_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stories.Author', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='story',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created date'),
        ),
        migrations.AddField(
            model_name='story',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Updated date'),
        ),
    ]
