# Generated by Django 3.0.7 on 2020-07-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20200701_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover_image',
            field=models.ImageField(default='bg_4.jpg', upload_to='recipes/', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(default='stories/bg_4.jpg', upload_to='stories/', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='Story image'),
        ),
    ]
