# Generated by Django 3.0.6 on 2020-06-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20200622_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(default='stories/bg_4.jpg', upload_to='stories', verbose_name='Cover image'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='stories', verbose_name='Story image'),
        ),
    ]
