# Generated by Django 3.0.6 on 2020-06-07 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20200607_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_reply',
            old_name='message',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='author',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='author',
            name='graduated_from',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(blank=True, max_length=50, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='category',
            name='stories',
            field=models.ManyToManyField(to='stories.Story', verbose_name='Story'),
        ),
        migrations.AddField(
            model_name='category',
            name='story_category',
            field=models.CharField(default='Foods', max_length=50, verbose_name='Story category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stories.Author', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stories.Story', verbose_name='Story'),
        ),
    ]
