# Generated by Django 3.0.6 on 2020-06-08 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20200607_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stories.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prepare_time',
            field=models.CharField(max_length=50, verbose_name='Prepare time'),
        ),
    ]
