# Generated by Django 3.0.7 on 2020-07-02 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20200701_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='stories.Comment', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='storyimage',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stories.Story'),
        ),
    ]
