# Generated by Django 3.0.7 on 2020-07-07 07:43

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('stories', '0007_auto_20200702_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='stories.TaggedStory', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
