# Generated by Django 3.0.7 on 2020-07-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_auto_20200707_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='Cover image'),
        ),
    ]
