# Generated by Django 3.0.7 on 2020-07-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_auto_20200707_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='prepare_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Prepare time'),
        ),
    ]
