# Generated by Django 3.0.6 on 2020-06-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_footerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerinfo',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
    ]
