# Generated by Django 3.0.7 on 2020-07-10 09:36

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('stories', '0012_auto_20200709_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggedstory',
            old_name='content_object',
            new_name='story_tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='stories.TaggedStory', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='taggedstory',
            name='recipe_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='stories.Recipe'),
        ),
    ]
