# Generated by Django 3.0.7 on 2020-07-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_auto_20200710_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggedstory',
            old_name='recipe_tag',
            new_name='content_object_recipe',
        ),
        migrations.RenameField(
            model_name='taggedstory',
            old_name='story_tag',
            new_name='content_object_story',
        ),
    ]
