# Generated by Django 3.0.6 on 2020-06-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_auto_20200613_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Source'),
        ),
    ]
