# Generated by Django 3.0.7 on 2020-07-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_auto_20200710_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggedstory',
            old_name='content_object_recipe',
            new_name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedstory',
            name='content_object_story',
        ),
    ]
