# Generated by Django 3.0.6 on 2020-06-16 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_contact_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='authors',
            field=models.ManyToManyField(related_name='recipes', to='stories.Author', verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='stories.Author', verbose_name='Author'),
        ),
    ]
