# Generated by Django 3.0.6 on 2020-06-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0016_auto_20200616_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/', verbose_name='Image'),
        ),
    ]
