# Generated by Django 3.0.7 on 2020-10-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0016_auto_20200710_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
