# Generated by Django 3.0.6 on 2020-06-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0017_auto_20200616_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(upload_to='recipes/', verbose_name='Recipe Image'),
        ),
    ]
