# Generated by Django 3.0.6 on 2020-06-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0019_auto_20200616_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='recipes',
            field=models.ManyToManyField(related_name='tags', to='stories.Recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='stories',
            field=models.ManyToManyField(related_name='tags', to='stories.Story', verbose_name='Story'),
        ),
    ]
