# Generated by Django 3.0.6 on 2020-06-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0020_auto_20200616_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tags'),
        ),
    ]
