# Generated by Django 3.0.6 on 2020-06-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0021_story_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='tag',
            new_name='tag_list',
        ),
    ]
