# Generated by Django 3.0.6 on 2020-06-17 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0022_auto_20200616_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='tag_list',
        ),
    ]
