# Generated by Django 3.0.6 on 2020-06-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0023_remove_story_tag_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_count',
            field=models.IntegerField(default=0, verbose_name='Story count'),
        ),
    ]
