# Generated by Django 3.0.6 on 2020-06-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0024_story_story_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_count',
            field=models.IntegerField(default=0, verbose_name='Recipe count'),
            preserve_default=False,
        ),
    ]
