# Generated by Django 3.0.6 on 2020-06-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0025_recipe_recipe_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='user', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_count',
            field=models.IntegerField(default=0, verbose_name='Recipe count'),
        ),
    ]
